name = "aimmar-blog-api"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
ADMIN_EMAIL = "g29tony@gmail.com"
ACCESS_TEAM_DOMAIN = "aimmar.cloudflareaccess.com"
ACCESS_AUD = "18f9ac73bd30564cf9894534be011b4dbb1e5d9e4ec5a1ede19e4fdb931aaf3a"

[[d1_databases]]
binding = "DB"
database_name = "aimmar_blog"
database_id = "08795aac-879e-4b87-b460-42a1b4aa3999"
